// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VisareBR.Core.Data;

#nullable disable

namespace VisareBR.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806040651_AddYoutubeChannelIdToSettings")]
    partial class AddYoutubeChannelIdToSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VisareBR.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeaturedImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReadTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInVisaDropdown")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.ArticleBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleBlocks");

                    b.HasDiscriminator<string>("BlockType").HasValue("ArticleBlock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VisareBR.Core.Entities.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarouselItems");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Ds160Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ds160Submissions");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "O visto americano é um documento que permite a entrada nos Estados Unidos para diversos fins, como turismo, negócios, estudo ou trabalho. Brasileiros precisam de visto para entrar nos EUA. A VisareBR auxilia em todo o processo de solicitação.",
                            Category = "Geral",
                            DisplayOrder = 1,
                            IsActive = true,
                            Question = "O que é o visto americano e quem precisa dele?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "O tempo varia conforme a demanda do consulado. Após o pagamento das taxas e preenchimento do DS-160, é possível agendar a entrevista. A disponibilidade de datas varia entre consulados. Após a entrevista, se aprovado, o passaporte com o visto geralmente é devolvido em até 10 dias úteis.",
                            Category = "Geral",
                            DisplayOrder = 2,
                            IsActive = true,
                            Question = "Quanto tempo demora para conseguir o visto americano?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "O visto B1/B2 é o mais comum e serve tanto para turismo quanto para negócios. O B1 (negócios) é para reuniões, conferências e consultas. O B2 (turismo) é para férias, visitar amigos/família e tratamento médico. Geralmente, ambos vêm juntos no mesmo visto.",
                            Category = "Processo",
                            DisplayOrder = 3,
                            IsActive = true,
                            Question = "Qual a diferença entre visto de turismo e visto de negócios?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Sim, a VisareBR conta com serviços de antecipação de datas para os próximos 60 dias. Temos um monitoramento de datas constante em que conseguimos pegar datas que liberam por diversos motivos como cancelamento de agendamento, reagendamento ou novos lotes de datas disponibilizados pelo Consulado.",
                            Category = "Agendamento",
                            DisplayOrder = 4,
                            IsActive = true,
                            Question = "É possível adiantar as datas da entrevista?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Você precisará de: passaporte válido, formulário DS-160 preenchido, comprovante de pagamento das taxas (MRV), foto recente no padrão americano, e documentos que comprovem vínculos com o Brasil (emprego, propriedades, vínculos familiares) e capacidade financeira para a viagem.",
                            Category = "Documentos",
                            DisplayOrder = 5,
                            IsActive = true,
                            Question = "Quais documentos preciso para solicitar o visto americano?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "O DS-160 é o formulário de solicitação de visto não-imigrante. Deve ser preenchido online em inglês no site do Departamento de Estado dos EUA. Ele contém informações pessoais, sobre a viagem, educação, trabalho e segurança. É importante preencher com atenção e veracidade. A VisareBR auxilia no preenchimento correto.",
                            Category = "Documentos",
                            DisplayOrder = 6,
                            IsActive = true,
                            Question = "O que é o formulário DS-160?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "A entrevista é presencial no consulado americano. Você apresentará seus documentos ao oficial consular, que fará perguntas sobre sua viagem, vínculos com o Brasil e situação financeira. É importante ser honesto e objetivo nas respostas. A VisareBR prepara você com orientações específicas sobre a entrevista.",
                            Category = "Entrevista",
                            DisplayOrder = 7,
                            IsActive = true,
                            Question = "Como funciona a entrevista no consulado?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Os principais motivos incluem: falta de comprovação de vínculos com o Brasil, suspeita de intenção de imigração, informações inconsistentes ou falsas no formulário ou entrevista, falta de recursos financeiros comprovados, e histórico de violação de leis de imigração. A preparação adequada reduz muito o risco de negativa.",
                            Category = "Entrevista",
                            DisplayOrder = 8,
                            IsActive = true,
                            Question = "Quais são os principais motivos de negativa de visto?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Não é obrigatório, mas uma assessoria especializada como a VisareBR aumenta significativamente suas chances de aprovação. Auxiliamos no preenchimento correto do DS-160, análise de documentos, preparação para a entrevista e acompanhamento de todo o processo, evitando erros que podem causar negativas.",
                            Category = "Geral",
                            DisplayOrder = 9,
                            IsActive = true,
                            Question = "Preciso de assessoria para tirar o visto americano?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Sim, em alguns casos é possível renovar através do programa de Renovação sem Entrevista. Alguns dos requisitos são ter o visto anterior ainda válido ou vencido há menos de 48 meses, mesma categoria de visto, e nunca ter tido problemas de imigração nos EUA. A VisareBR verifica sua elegibilidade.",
                            Category = "Processo",
                            DisplayOrder = 10,
                            IsActive = true,
                            Question = "É possível renovar o visto americano sem entrevista?"
                        });
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Padrão",
                            ProcessingTime = "4 dias úteis"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Intermediário",
                            ProcessingTime = "2 dias úteis"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Premium",
                            ProcessingTime = "24 horas"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "VIP",
                            ProcessingTime = "24 horas"
                        });
                });

            modelBuilder.Entity("VisareBR.Core.Entities.PlanBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanBenefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avaliação de perfil",
                            IsIncluded = true,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Preenchimento do DS-160",
                            IsIncluded = true,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Criação de conta no consulado",
                            IsIncluded = true,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Defesa em caso de negativa",
                            IsIncluded = false,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Atendimento exclusivo",
                            IsIncluded = false,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Avaliação de perfil",
                            IsIncluded = true,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Preenchimento do DS-160",
                            IsIncluded = true,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Criação de conta no consulado",
                            IsIncluded = true,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Defesa em caso de negativa",
                            IsIncluded = true,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Atendimento exclusivo",
                            IsIncluded = false,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tudo do Intermediário",
                            IsIncluded = true,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Atendimento exclusivo",
                            IsIncluded = true,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Isenção de taxa na 1ª renovação",
                            IsIncluded = true,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Representação e eTA Canadá",
                            IsIncluded = false,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tudo do Premium",
                            IsIncluded = true,
                            PlanId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Representação em processos",
                            IsIncluded = true,
                            PlanId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "eTA Canadá grátis",
                            IsIncluded = true,
                            PlanId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Isenção em 2 renovações",
                            IsIncluded = true,
                            PlanId = 4
                        });
                });

            modelBuilder.Entity("VisareBR.Core.Entities.PlanPricingTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanPricingTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantCount = 1,
                            PlanId = 1,
                            TotalPrice = 549.00m
                        },
                        new
                        {
                            Id = 2,
                            ApplicantCount = 2,
                            PlanId = 1,
                            TotalPrice = 999.00m
                        },
                        new
                        {
                            Id = 3,
                            ApplicantCount = 1,
                            PlanId = 2,
                            TotalPrice = 749.00m
                        },
                        new
                        {
                            Id = 4,
                            ApplicantCount = 2,
                            PlanId = 2,
                            TotalPrice = 1399.00m
                        },
                        new
                        {
                            Id = 5,
                            ApplicantCount = 1,
                            PlanId = 3,
                            TotalPrice = 949.00m
                        },
                        new
                        {
                            Id = 6,
                            ApplicantCount = 2,
                            PlanId = 3,
                            TotalPrice = 1799.00m
                        },
                        new
                        {
                            Id = 7,
                            ApplicantCount = 1,
                            PlanId = 4,
                            TotalPrice = 1299.00m
                        },
                        new
                        {
                            Id = 8,
                            ApplicantCount = 2,
                            PlanId = 4,
                            TotalPrice = 2399.00m
                        });
                });

            modelBuilder.Entity("VisareBR.Core.Entities.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric1Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric1Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric2Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric2Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric3Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric3Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsappDefaultMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.StandaloneService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StandaloneServices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Serviço de Passaporte",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Emissão do eTA (eletrônico canadense)",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Emissão do ESTA (eletrônico americano)",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Serviço de Entrega Premium (renovação sem entrevista)",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Visto Canadá Turismo",
                            Price = 490.00m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Reversão de Negativa",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Somente Agendamento",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Antecipação de Entrevista",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Simulação de Entrevista",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "",
                            Features = "",
                            IconName = "Briefcase",
                            IsActive = true,
                            Name = "Revisão do DS-160",
                            Price = 350.00m
                        });
                });

            modelBuilder.Entity("VisareBR.Core.Entities.ButtonBlock", b =>
                {
                    b.HasBaseType("VisareBR.Core.Entities.ArticleBlock");

                    b.Property<string>("HexColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("button");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.ImageBlock", b =>
                {
                    b.HasBaseType("VisareBR.Core.Entities.ArticleBlock");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("image");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.RecommendationBlock", b =>
                {
                    b.HasBaseType("VisareBR.Core.Entities.ArticleBlock");

                    b.Property<string>("RecommendedArticleIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("recommendation");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.TextBlock", b =>
                {
                    b.HasBaseType("VisareBR.Core.Entities.ArticleBlock");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.VideoBlock", b =>
                {
                    b.HasBaseType("VisareBR.Core.Entities.ArticleBlock");

                    b.Property<string>("EmbedData")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("video");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisareBR.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Article", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.ArticleBlock", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.Article", "Article")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.PlanBenefit", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.Plan", "Plan")
                        .WithMany("Benefits")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.PlanPricingTier", b =>
                {
                    b.HasOne("VisareBR.Core.Entities.Plan", "Plan")
                        .WithMany("PricingTiers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Article", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("VisareBR.Core.Entities.Plan", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("PricingTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
